// Color constants
export const COLORS = {
  GREEN_FILL: '#061019',
  RED_FILL: '#061019', 
  GREEN_STROKE: '#34CF82',
  RED_STROKE: '#FF7F7B',
  NAVY_FILL: '#2a3f50',
  MAIN_NODE_STROKE: '#061019',
  WHITE: '#FFFFFF',
  SHARED_HIGHLIGHT: '#008EFF',
  BACKGROUND: '#061019',
  BORDER: '#2a3f50',
  SUCCESS: '#34CF82',
  ERROR: '#FF7F7B'
};

// Size constants
export const SIZES = {
  MAIN_NODE_RADIUS: 30,
  UNIFORM_NODE_RADIUS: 24,
  AGGREGATED_LINK_WIDTH: 0.75,
  TRANSACTION_LINK_WIDTH: 0.1,
  MAIN_TO_MAIN_LINK_WIDTH: 1,
  NODE_STROKE_WIDTH: 2,
  HIGHLIGHT_STROKE_WIDTH: 3.4
};

// Physics simulation constants
export const PHYSICS = {
  PENDULUM_DISTANCE: 180,
  MAIN_TO_MAIN_DISTANCE: 120,
  LINK_STRENGTH: 0.8,
  MAIN_NODE_CHARGE: -600,
  COUNTERPARTY_CHARGE: -150,
  COLLISION_STRENGTH: 0.7,
  VELOCITY_DECAY: 0.7,
  MAIN_NODE_BUFFER_MULTIPLIER: 6,
  ARROW_REPULSION_DISTANCE: 90
};

// Timeframe options
export const TIMEFRAMES = {
  '30D': 30,
  '90D': 90,
  '1Y': 365,
  '5Y': 365 * 5
};

// UI constants
export const UI = {
  DRAG_THRESHOLD: 5,
  TOOLTIP_OFFSET: 10,
  CONTEXT_MENU_Z_INDEX: 1000,
  FONT_SIZE_REDUCTION: 0.27,
  MIN_FONT_SIZE: 7.2,
  CURVE_SPREAD_RANGE: 1.0,
  CURVE_BASE_DISTANCE: 25,
  CURVE_SPREAD_MULTIPLIER: 40
};

// Default values
export const DEFAULTS = {
  SCALE_FACTOR: 1,
  SIZE_METRIC: 'uniform',
  LABEL_MODE: 'address',
  TIMEFRAME: '30D',
  RANGE_MIN: '1',
  SHOW_SMART_CONTRACTS: true,
  SHOW_EXCHANGES: true,
  HIGHLIGHT_SHARED: false
}; 